// Enums para TypeScript y PostgreSQL

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  PLANIFICADOR = 'PLANIFICADOR',
  APROBADOR = 'APROBADOR',
  CONSULTA = 'CONSULTA',
  DOCTOR = 'DOCTOR', // Sprint 3
  RECEPCIONISTA = 'RECEPCIONISTA', // Sprint 3
}

export enum InstitutionStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  INACTIVE = 'INACTIVE',
}

export enum InstitutionType {
  CLINIC = 'CLINIC',
  HOSPITAL = 'HOSPITAL',
  LAB = 'LAB',
  OTHER = 'OTHER',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  TRIAL = 'TRIAL',
}

export enum ShiftType {
  MORNING   = 'MORNING',    // Mañana:    07:00–13:00, 6h, demanda mínima 3 personas
  AFTERNOON = 'AFTERNOON',  // Tarde:     13:00–19:00, 6h, demanda mínima 1 persona
  NIGHT_6H  = 'NIGHT_6H',   // Noche 6h:  19:00–01:00, 6h, demanda mínima 1 persona
  NIGHT_12H = 'NIGHT_12H',  // Noche 12h: 19:00–07:00, 12h, demanda mínima 1 persona
  DAY_OFF   = 'DAY_OFF',    // Libre:     sin horas, sin demanda
  SPECIAL   = 'SPECIAL',    // Especial:  configuración libre
}

// Sprint 3 - Módulo de Citas
export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum DocumentType {
  CC = 'CC', // Cédula de Ciudadanía
  TI = 'TI', // Tarjeta de Identidad
  CE = 'CE', // Cédula de Extranjería
  PA = 'PA', // Pasaporte
}

export enum AuditEventType {
  INSTITUTION_CREATED = 'INSTITUTION_CREATED',
  INSTITUTION_UPDATED = 'INSTITUTION_UPDATED',
  INSTITUTION_SUSPENDED = 'INSTITUTION_SUSPENDED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  // Sprint 2 - Configuración Operativa
  SERVICE_CREATED = 'SERVICE_CREATED',
  SERVICE_UPDATED = 'SERVICE_UPDATED',
  SERVICE_DELETED = 'SERVICE_DELETED',
  SHIFT_CREATED = 'SHIFT_CREATED',
  SHIFT_UPDATED = 'SHIFT_UPDATED',
  SHIFT_DELETED = 'SHIFT_DELETED',
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_UPDATED = 'CONTRACT_UPDATED',
  CONTRACT_DELETED = 'CONTRACT_DELETED',
  HOLIDAY_CREATED = 'HOLIDAY_CREATED',
  HOLIDAY_UPDATED = 'HOLIDAY_UPDATED',
  HOLIDAY_DELETED = 'HOLIDAY_DELETED',
  // Sprint 3 - Pacientes y Citas
  PATIENT_CREATED = 'PATIENT_CREATED',
  PATIENT_UPDATED = 'PATIENT_UPDATED',
  PATIENT_DELETED = 'PATIENT_DELETED',
  APPOINTMENT_CREATED = 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  APPOINTMENT_DELETED = 'APPOINTMENT_DELETED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_COMPLETED = 'APPOINTMENT_COMPLETED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  // Sprint 3 - Médicos y Especialidades
  SPECIALTY_CREATED = 'SPECIALTY_CREATED',
  SPECIALTY_UPDATED = 'SPECIALTY_UPDATED',
  SPECIALTY_DELETED = 'SPECIALTY_DELETED',
  DOCTOR_CREATED = 'DOCTOR_CREATED',
  DOCTOR_UPDATED = 'DOCTOR_UPDATED',
  DOCTOR_DELETED = 'DOCTOR_DELETED',
  // Sprint 4 - Disponibilidad
  SCHEDULE_CREATED = 'SCHEDULE_CREATED',
  SCHEDULE_UPDATED = 'SCHEDULE_UPDATED',
  SCHEDULE_DELETED = 'SCHEDULE_DELETED',
  BLOCK_CREATED = 'BLOCK_CREATED',
  BLOCK_DELETED = 'BLOCK_DELETED',
  RECURRING_APPOINTMENT_CREATED = 'RECURRING_APPOINTMENT_CREATED',
  RECURRING_APPOINTMENT_CANCELLED = 'RECURRING_APPOINTMENT_CANCELLED',
  // Sprint 8 - Mallas de Turnos
  WORK_SCHEDULE_CREATED = 'WORK_SCHEDULE_CREATED',
  WORK_SCHEDULE_UPDATED = 'WORK_SCHEDULE_UPDATED',
  WORK_SCHEDULE_SUBMITTED = 'WORK_SCHEDULE_SUBMITTED',
  WORK_SCHEDULE_APPROVED = 'WORK_SCHEDULE_APPROVED',
  WORK_SCHEDULE_REJECTED = 'WORK_SCHEDULE_REJECTED',
  WORK_SCHEDULE_VALIDATED = 'WORK_SCHEDULE_VALIDATED',
  WORK_SCHEDULE_DELETED = 'WORK_SCHEDULE_DELETED',
  ASSIGNMENT_CREATED = 'ASSIGNMENT_CREATED',
  ASSIGNMENT_UPDATED = 'ASSIGNMENT_UPDATED',
  ASSIGNMENT_DELETED = 'ASSIGNMENT_DELETED',
}

// Sprint 4 - Frecuencia de Citas Recurrentes
export enum RecurringFrequency {
  WEEKLY = 'WEEKLY',
  BIWEEKLY = 'BIWEEKLY',
  MONTHLY = 'MONTHLY',
}

// Sprint 4 - Estado de un slot de disponibilidad
export enum SlotStatus {
  FREE = 'FREE',
  BOOKED = 'BOOKED',
  BLOCKED = 'BLOCKED',
}
